dekadowki.poburski.pl/Controllers/DashboardController.cs
using dekadowki.poburski.pl.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace dekadowki.poburski.pl.Controllers
{
    public class DashboardController : Controller
    {
        List<Budowa> budowy = Help.GetBudowy();

        // GET: Dashboard
        public ActionResult Index()
        {
            //802 - xeos
            var xeos = budowy.Where(b => b.Numer == "802").First();
            xeos.Nazwa = "Xeos " + xeos.Nazwa;

            var currentBudowa = budowy[0];
            if (Session["Budowa"] != null)
            {
                currentBudowa = (Budowa)Session["Budowa"];
            }

            Tydzien currentWeek = Session["Tydzien"] != null ? (Tydzien)Session["Tydzien"] : null;

            try
            {
                if (currentWeek == null)
                {
                    currentWeek = Help.GetTydzien(Convert.ToInt32(Response.Cookies["Tydzien"].Value));
                }
            }
            catch (Exception ex)
            {
                currentWeek = Help.GetTydzien(Help.GetCurrentWeek());
                Debug.WriteLine(ex.Message);
            }

            try
            {
                DashboardViewModel dvm = new DashboardViewModel();
                dvm.Brygada = Session["NowaBrygada"] != null ? (List<Brygada>)Session["NowaBrygada"] : null;
                dvm.DniTygodnia = Help.GetDniTygodnia(dvm.Brygada.Count, currentWeek, dvm.Brygada[0].Id, dvm.Brygada, currentBudowa.Id);
                dvm.Tydzien = currentWeek;
                dvm.Brygadzista = dvm.Brygada[0];
                ViewBag.Message = "";
                ViewBag.ColorMessage = "";
                ViewBag.Budowy = budowy;
                ViewBag.Podpisy = Help.GetPodpisy(dvm, currentBudowa);
                ViewBag.Tydzien = currentWeek;

                //Sessions
                Session["Tydzien"] = currentWeek;
                Session["DVM"] = dvm;
                Session["Budowa"] = currentBudowa;

                //Cookie
                Response.Cookies["Tydzien"].Value = currentWeek.getRokTydzien();
                Response.Cookies["Tydzien"].Expires = DateTime.Now.AddMinutes(15);

                return View(dvm);
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Index2(string message, string colorMessage, string serwis, bool? drukuj)
        {
            var currentBudowa = budowy[0];
            if (Session["Budowa"] != null)
            {
                currentBudowa = (Budowa)Session["Budowa"];
            }

            Tydzien currentWeek = Help.GetTydzien(Help.GetCurrentWeek());
            if (Session["Tydzien"] != null)
            {
                currentWeek = (Tydzien)Session["Tydzien"];
            }
            else
            {
                try
                {
                    currentWeek = Help.GetTydzien(Response.Cookies["Tydzien"].Value);
                }
                catch (Exception e)
                {
                    Debug.WriteLine(e.Message);
                    currentWeek = Help.GetTydzien(Help.GetCurrentWeek());
                }
            }

            DashboardViewModel dvm = new DashboardViewModel();
            dvm.Brygada = Help.GetBrygada(Help.GetIdIntranetFromDb(User.Identity.Name), true);
            if (Session["NowaBrygada"] != null)
            {
                dvm.Brygada = (List<Brygada>)Session["NowaBrygada"];
            }
            dvm.DniTygodnia = Help.GetDniTygodnia(dvm.Brygada.Count, currentWeek, dvm.Brygada[0].Id, dvm.Brygada, currentBudowa.Id);
            dvm.Tydzien = currentWeek;
            dvm.Brygadzista = dvm.Brygada[0];
            ViewBag.Message = string.IsNullOrEmpty(message) ? "" : message;
            ViewBag.ColorMessage = string.IsNullOrEmpty(colorMessage) ? "" : colorMessage;
            ViewBag.Budowy = budowy;
            ViewBag.WybranaBudowa = currentBudowa;
            ViewBag.Serwis = string.IsNullOrEmpty(serwis) ? null : serwis;
            ViewBag.Podpisy = Help.GetPodpisy(dvm, currentBudowa);
            ViewBag.Print = drukuj;

            //Sessions
            Session["Tydzien"] = currentWeek;
            Session["DVM"] = dvm;
            Session["Budowa"] = currentBudowa;

            if (currentWeek != null)
            {
                return View("Index", dvm);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Print()
        {
            var wybranaBudowa = (Budowa)Session["Budowa"];
            ViewBag.WybranaBudowa = wybranaBudowa;
            ViewBag.Tydzien = (Tydzien)Session["Tydzien"];
            DashboardViewModel dvm = (DashboardViewModel)Session["DVM"];
            ViewBag.Podpisy = Help.GetPodpisy(dvm, wybranaBudowa);

            return View(dvm);
        }

        [HttpPost]
        public ActionResult SaveDashboard(DashboardViewModel dvm = null, List<string> imageData = null, FormCollection collection = null)
        //public ActionResult SaveDashboard(DashboardViewModel dvm, string budowa, string komenda, List<string> imageData, FormCollection collection)
        {
            if (dvm == null || collection == null)
            {
                try
                {
                    var json = JsonConvert.SerializeObject(dvm, Formatting.Indented);
                    var json2 = JsonConvert.SerializeObject(collection, Formatting.Indented);
                    var json3 = JsonConvert.SerializeObject(imageData, Formatting.Indented);
                    var filename = AppDomain.CurrentDomain.BaseDirectory + "Logi\\" + "Dashboard\\BlądDVM"  + DateTime.Now.ToString("dd-MM-yyyy") + ".txt";
                    var sw = new System.IO.StreamWriter(filename, true);
                    sw.WriteLine(DateTime.Now.ToString() + Environment.NewLine + json.ToString() + Environment.NewLine + "***************************************");
                    sw.Close();

                    Session["AdditionalMessage"] = "Coś poszło nie tak. Logi zapisane.";
                }
                catch (Exception e)
                {
                    Debug.WriteLine(e.Message);
                }
                return RedirectToAction("Index", "Home");
            }

            Budowa currentBudowa;
            string budowa = collection["budowa"].ToString();
            string komenda = collection["komenda"].ToString();
            string serwis = "";
            try
            {
                currentBudowa = budowy.FirstOrDefault(m => m.Id == Convert.ToInt32(budowa));
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
                currentBudowa = new Budowa(0, budowa, "0");
                serwis = currentBudowa.Nazwa;
            }

            //try
            //{
            dvm.Brygadzista = dvm.Brygada[0];
            dvm.Tydzien = (Tydzien)Session["Tydzien"]; //z sesji
            if (dvm.Tydzien == null) //z ciasteczka
            {
                dvm.Tydzien = Help.GetTydzien(Response.Cookies["Tydzien"].Value);
                Session["Tydzien"] = dvm.Tydzien;
            }
            if (dvm.Tydzien == null) //z kolekcji
            {
                dvm.Tydzien = Help.GetTydzien(Convert.ToInt32(collection["tydzien"]));
                Session["Tydzien"] = dvm.Tydzien;
                Response.Cookies.Add(new HttpCookie("Tydzien", dvm.Tydzien.getRokTydzien()));
            }
            //}
            //catch (Exception e)
            //{
            //    Debug.WriteLine(e.Message);

            //}

            string message = "";
            string colorMessage = "black";

            ViewBag.WybranaBudowa = currentBudowa;
            ViewBag.Budowy = budowy;

            //Sessions
            Session["Tydzien"] = dvm.Tydzien;
            Session["DVM"] = dvm;
            Session["Budowa"] = currentBudowa;

            if (komenda == "0" || komenda == "" || komenda == "2")
            {
                //Zapis do bazy
                //try
                //{
                pobiNTRANETDataContext dc = new pobiNTRANETDataContext();
                Help.SaveWeekToDatabase(dvm, currentBudowa, Server.MapPath("~/Content/signatures"), imageData, Server.MapPath("~/Logi/Dashboard/"), dvm.Tydzien);
                message = string.Format("Zapisano zmiany ({0})", DateTime.Now);
                colorMessage = "#00872B";
                //}
                //catch (Exception blad003)
                //{
                //    message = string.Format("Coś poszło nie tak. {0}{1}{2}", blad003.Message, Environment.NewLine, JsonConvert.SerializeObject(dvm, Formatting.Indented).ToString());
                //    colorMessage = "#FF3232";
                //}

                ViewBag.Message = message;
                ViewBag.ColorMessage = colorMessage;
                ViewBag.Podpisy = Help.GetPodpisy(dvm, currentBudowa);
                ViewBag.Serwis = serwis;

                //Sessions
                Session["Tydzien"] = dvm.Tydzien;
                Session["DVM"] = dvm;
                Session["Budowa"] = currentBudowa;

                return View("Index", dvm);
            }
            else
            {
                message = string.Format("zmieniono_budowe");
                colorMessage = "#4286f4";
            }

            dvm.DniTygodnia = Help.GetDniTygodnia(dvm.Brygada.Count, dvm.Tydzien, dvm.Brygada[0].Id, dvm.Brygada, currentBudowa.Id);
            ViewBag.WybranaBudowa = currentBudowa;
            ViewBag.Budowy = budowy;
            ViewBag.Podpisy = Help.GetPodpisy(dvm, currentBudowa);

            //Sessions
            Session["Tydzien"] = dvm.Tydzien;

dekadowki.poburski.pl/Views/Home/Blockade.cshtml
@model IEnumerable<dekadowki.poburski.pl.Models.Tydzien>
@using dekadowki.poburski.pl.Models

@{
    ViewBag.Title = "Odblokuj lub zablokuj tydzień";
    Layout = "~/Views/Shared/_Layout.cshtml";

    List<int> lata = (List<int>)ViewBag.Lata;
}

<h2>Odblokuj lub zablokuj tydzień</h2>

@using (Html.BeginForm("Blockade", "Home", FormMethod.Post))
{
    <div class="form-group">
        <label for="answerInput">Zmień rok: </label>
        <select name="year" id="year" class="form-control">
            @foreach (var rok in lata)
            {
                if (DateTime.Now.Year != rok)
                {
                    <option value="@rok">@rok</option>
                }
                else
                {
                    <option value="@rok" selected>@rok</option>
                }
            }
        </select>
    </div>
    <input type="submit" value="Przejdź" class="btn btn-primary" />
}
<hr />
<h4>Odblokuj</h4>
@foreach (var tydzien in Model)
{
    <table>
        @if (tydzien.getZablokowany() == 1)
        {
            <tr>
                <td>@string.Format("{1} - {2} [Tydzień: {0}]", tydzien.getRokTydzien(), Help.GetDayOfWeek(tydzien.getRokTydzien(), 1).Substring(0, 5), Help.GetDayOfWeek(tydzien.getRokTydzien(), 7).Substring(0, 5))</td>
                <td>
                    <a href='@Url.Action("Unlock", "Home", new { year = Request["year"], id = tydzien.getId() })'>
                        <img src='@Url.Content("~/Content/images/unlock.ico")' width="25" />
                    </a>
                </td>
            </tr>
        }
    </table>
}
<h4>Zablokuj</h4>
@if (((List<Tydzien>)Model).Count > 0)
{
    foreach (var tydzien in Model)
    {
        <table>
            @if (tydzien.getZablokowany() != 1)
            {
                <tr>
                    <td>@string.Format("{1} - {2} [Tydzień: {0}]", tydzien.getRokTydzien(), Help.GetDayOfWeek(tydzien.getRokTydzien(), 1).Substring(0, 5), Help.GetDayOfWeek(tydzien.getRokTydzien(), 7).Substring(0, 5))</td>
                    <td>
                        <a href='@Url.Action("Lock", "Home", new { year = Request["year"], id = tydzien.getId() })'>
                            <img src='@Url.Content("~/Content/images/lock.png")' width="25" />
                        </a>
                    </td>
                </tr>
            }
        </table>
    }
}
else
{
    <p>BRAK DO ZABLOKOWANIA</p>
}

dekadowki.poburski.pl/Views/Home/Filtrowanie.cshtml
@using dekadowki.poburski.pl.Models
@{
    Layout = null;

    var filtrGodziny = new List<AspNetGodziny>();

    if(Session["filtrGodziny"] != null)
    {
        filtrGodziny = (List<AspNetGodziny>)Session["filtrGodziny"];
    }
    else
    {
        filtrGodziny = Help.GetGodzinyDoPogladu(User.Identity.Name);
    }
    Session["filtrGodziny"] = filtrGodziny;

    var brygadzisci = Session["filtrBrygadzisci"] == null ? Help.GetBrygadzistowZGodzin(filtrGodziny) : (List<Brygadzista>)Session["filtrBrygadzisci"];
    Session["filtrBrygadzisci"] = brygadzisci;
    var budowy = Session["filtrBudowy"] == null ? Help.GetBudowyZGodzin(filtrGodziny) : (List<Budowa>)Session["filtrBudowy"];
    Session["filtrBudowy"] = budowy;
    var tygodnie = Session["filtrTygodni"] == null ? Help.GetTygodnieZGodzin(filtrGodziny) : (List<Tydzien>)Session["filtrTygodni"];
    Session["filtrTygodni"] = tygodnie;

    int filtrBudowa = Session["FiltrBudowa"] != null ? Convert.ToInt32(Session["FiltrBudowa"]) : 0;
    int filtrBrygadzista = Session["FiltrBrygadzista"] != null ? Convert.ToInt32(Session["FiltrBrygadzista"]) : 0;
    int filtrTydzien = Session["FiltrTydzien"] != null ? Convert.ToInt32(Session["FiltrTydzien"]) : 0;
}

@using (Html.BeginForm("FiltrujPodglad", "Home", FormMethod.Post, new { @class = "form-inline" }))
{
    <div class="form-group no-print">
        <label class="sr-only" for="budowa">Budowa:</label>
        <select id="budowa" name="budowa" class="form-control">
            @if (filtrBudowa == 0)
            {
                <option value="0" selected>Wszystkie budowy</option>
            }
            else
            {
                <option value="0">Wszystkie budowy</option>
            }
            @foreach (var bud in budowy)
            {
                if (bud.Id != filtrBudowa)
                {
                    <option value="@bud.Id">@bud.Nazwa</option>
                }
                else
                {
                    <option value="@bud.Id" selected>@bud.Nazwa</option>
                }
            }
        </select>
    </div>
    <div class="form-group no-print">
        <label class="sr-only" for="tydzien">Tydzien:</label>
        <select id="tydzien" name="tydzien" class="form-control">
            @if (filtrTydzien == 0)
            {
                <option value="0" selected>Wszystkie tygodnie</option>
            }
            else
            {
                <option value="0">Wszystkie tygodnie</option>
            }
            @foreach (var tyd in tygodnie)
            {
                if (tyd != null)
                {
                    if (tyd.getRokTydzien() != Help.GetTydzien(filtrTydzien).getRokTydzien())
                    {
                        <option value="@tyd.getId()">@string.Format("{1} - {2} [Tydzień: {0}]", tyd.getRokTydzien(), Help.GetDayOfWeek(tyd.getRokTydzien(), 1), Help.GetDayOfWeek(tyd.getRokTydzien(), 7))</option>
                    }
                    else
                    {
                        <option value="@tyd.getId()" selected>@string.Format("{1} - {2} [Tydzień: {0}]", tyd.getRokTydzien(), Help.GetDayOfWeek(tyd.getRokTydzien(), 1), Help.GetDayOfWeek(tyd.getRokTydzien(), 7))</option>
                    }
                }
            }
        </select>
    </div>
    <div class="form-group no-print">
        <label class="sr-only" for="brygadzista">Brygadzista:</label>
        <select id="brygadzista" name="brygadzista" class="form-control">
            @if (filtrBudowa == 0)
            {
                <option value="0" selected>Wszyscy brygadziści</option>
            }
            else
            {
                <option value="0">Wszyscy brygadziści</option>
            }
            @foreach (var bry in brygadzisci.OrderBy(b => b.nazwa).ToList())
            {
                if (bry.GetId() != filtrBrygadzista)
                {
                    <option value="@bry.id">@bry.nazwa</option>
                }
                else
                {
                    <option value="@bry.id" selected>@bry.nazwa</option>
                }
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary no-print">Filtruj</button>
}

dekadowki.poburski.pl/Views/Home/Index.cshtml
@using dekadowki.poburski.pl.Models
@{
    ViewBag.Title = "Strona główna";

    var errors = (List<string>)ViewBag.ErrorList;
    var brygada = (List<Brygada>)ViewBag.Brygada;
    var listaBrygadzistow = (List<Brygadzista>)ViewBag.Brygadzisci;
    var listaTygodni = (List<Tydzien>)ViewBag.Tydzien;

    bool admin = Help.SprawdzCzyAdmin(User.Identity.Name);
    var wiadomsci = (List<AspNetMessage>)ViewBag.Wiadomosci;

    var brygadzistaId = Help.GetIdIntranetFromDb(User.Identity.Name);
    var brygadzistaNazwa = Help.GetNameAndSurname(brygadzistaId);

    var currentRokTydzien = Help.GetCurrentWeek();

    bool przerwaTechniczna = false;
}

@if (wiadomsci.Count > 0)
{
    string message = "";
    foreach (var wiad in wiadomsci)
    {
        if (!message.Contains(wiad.tresc))
        {
            message += wiad.tresc + ". ";
        }
    }
    <script>
        var r = confirm("@message");
        if (r == true) {
            $.ajax({
                type: 'POST',
                url: "Home/ReadAllMessages",
                dataType: 'json',
                data: { brygadzistaid: @brygadzistaId },
                success: function (data) {
                },
                error: function (ex) {
                }
            });;
        }
    </script>
}

@foreach(var error in errors)
{
    <h2 style="color: red">@error</h2>
}

@if (przerwaTechniczna)
{
    <h1 style="color:red;">PRZERWA TECHNICZA</h1>
}
else
{
    if (admin)
    {
    <h1>Centrum administracyjne:</h1>
    <div class="row">
        <div class="col-md-6">
            <div class="card mdb-color lighten-2 text-center z-depth-2">
                <img class="card-img-top" src="~/Content/images/export.jpg" alt="Export do intranetu" height="200">
                <div class="card-body">
                    <p class=""><strong>Export do intranetu</strong></p>
                    @Html.ActionLink("Przejdź", "Index", "Export", new { id = -1, tydzien = "a", budowa = -1 }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mdb-color lighten-2 text-center z-depth-2">
                <img class="card-img-top" src="~/Content/images/blokada.jpg" alt="Zablokuj lub odblokuj tydzień" height="200">
                <div class="card-body">
                    <p class=""><strong>Zablokuj/Odblokuj tydzień</strong></p>
                    @Html.ActionLink("Przejdź", "Blockade", "Home", new { year = DateTime.Now.Year }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>
}
else
{
    int index = 0;

    <table style="width: 100%; margin-bottom: 20px;">
        <tr>
            <td style="width: 40%" align="left"><h1 style="float: left; margin-right: 20px;">Brygada: <br />@brygadzistaNazwa</h1></td>
            <td style="width: 25%" align="center">
                <label for="chooseTydzien">Wybierz tydzień: </label>
                <select onchange="changeSession(this)" id="chooseTydzien" name="tydzien" class="form-control">
                    @foreach (var tydzien in listaTygodni)
                    {
                        if (tydzien.getRokTydzien() != currentRokTydzien)
                        {
                            <option value="@tydzien.getId()">@string.Format("{1} - {2} [Tydzień: {0}]", tydzien.getRokTydzien(), Help.GetDayOfWeek(tydzien.getRokTydzien(), 1).Substring(0, 5), Help.GetDayOfWeek(tydzien.getRokTydzien(), 7).Substring(0, 5))</option>
                        }
                        else
                        {
                            <option value="@tydzien.getId()" selected>@string.Format("{1} - {2} [Tydzień: {0}]", tydzien.getRokTydzien(), Help.GetDayOfWeek(tydzien.getRokTydzien(), 1).Substring(0, 5), Help.GetDayOfWeek(tydzien.getRokTydzien(), 7).Substring(0, 5))</option>
                        }
                    }
                </select>
            </td>
            <td align="center" style="width: 25%"><p style="color: grey;">Bieżący tydzień: @currentRokTydzien</p></td>
            <td align="right" style="width: 10%"><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">Dodaj pracownika</button></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td colspan="2" align="right">
                <div class="row">
                    @Html.ActionLink("Przywróć", "GoBack", "Home", null, new { @class = "btn btn-primary btn-sm" })
                    @Html.ActionLink("Usuń wszystkich", "DeleteAll", "Home", null, new { @class = "btn btn-danger btn-sm" })
                </div>
            </td>
        </tr>
    </table>
    <div class="row">
        <table class="tabelaBrygada" border="1">
            <tr>
                <td align="right">Lp.</td>
                <td>Imię i nazwisko</td>
                <td>Brygadzista</td>
                <td align="center">Akcje</td>
            </tr>
            @foreach (var pracownik in brygada)
            {
                index++;
                var color = "white";
                if (brygadzistaId == pracownik.getId())
                {
                    color = "lightgray";
                }
                <tr style="background-color: @color">
                    <td align="right">@index</td>
                    <td width="800">@pracownik.getNazwa()</td>
                    @if (pracownik.getBrygadzistaId() != brygadzistaId && pracownik.getId() != brygadzistaId)
                    {
                        <td>@pracownik.getBrygadzistaNazwa()</td>
                    }
                    else
                    {
                        <td>&nbsp;</td>
                    }
                    @if (brygadzistaId != pracownik.getId())
                    {
                        <td align="center"><button type="button" class="btn btn-danger" onclick="confirmDelete(@string.Format("{0},'{1}'", pracownik.getId(), pracownik.getNazwa()))">x</button></td>
                    }
                    else
                    {
                        <td>&nbsp;</td>
                    }
                </tr>

            }
        </table>
    </div>
    <div class="row">
        @Html.ActionLink("Zatwierdź", "Index", "Dashboard", null, new { @class = "btn btn-success zatwierdzBrygade" })
    </div>
}


    <!--Error Modal-->
    <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="errorModalLabel">Wystąpiły następujące błędy</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        @foreach (var error in errors)
                        {
                            <p>@error</p>
                        }
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                </div>
            </div>
        </div>
    </div>

    <!--Add Modal-->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addModalLabel">Dodaj pracownika do brygady</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @using (Html.BeginForm("Add", "Home", FormMethod.Post))
                {
                    <div class="modal-body">

                        <div class="form-group">
                            <label for="answerInput">Wybierz pracownika: </label>
                            <input list="suggestionList" id="answerInput" class="form-control" required>
                            <datalist id="suggestionList">
                                @foreach (var pracownik in Help.GetBrygada(listaBrygadzistow[0].GetId(), true))
                                {
                                    <option data-value="@pracownik.getId()">@pracownik.getNazwa()</option>
                                }
                            </datalist>
                            <input type="hidden" name="answer" id="answerInput-hidden">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                        <input type="submit" value="Dodaj pracownika" class="btn btn-primary" />
                    </div>
                }
            </div>
        </div>
    </div>

    if (errors.Count != 0)
    {
        <script>
            $("#errorModal").show();
        </script>
    }

    <script>
        document.getElementById("chooseTydzien").onchange();

        function confirmDelete(id, nazwa) {
            window.location.href = "\\Home\\Delete?idpracownika=" + id;
        }

        function changeSession(tydzien) {
            $.ajax({
                type: 'POST',
                url: "Home/ChangeWeek",
                dataType: 'json',
                data: { tydzien: tydzien.value },
                success: function (data) {
                },
                error: function (ex) {
                }
            });
        }

        document.querySelector('input[list]').addEventListener('input', function (e) {
            var input = e.target,
                list = input.getAttribute('list'),
                options = document.querySelectorAll('#' + list + ' option'),
                hiddenInput = document.getElementById(input.id + '-hidden'),
                inputValue = input.value;

            hiddenInput.value = inputValue;

            for (var i = 0; i < options.length; i++) {
                var option = options[i];

                if (option.innerText === inputValue) {
                    hiddenInput.value = option.getAttribute('data-value');
                    break;
                }
            }
        });
    </script>
}